(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const m of r.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const S=document.querySelector(".yearNumber__year"),x=document.querySelector(".yearNumber__button"),l=document.querySelector(".yearNumber__description");x.addEventListener("click",()=>{let e=Number(S.value);console.log(e),e%4===0&&e%100!==0||e%400===0?(l.textContent="Ви народилися у високосний рік!",l.style.color="green",console.log("Ви народилися у високосний рік!"),l.style.color="none"):(l.textContent="Ви народилися не у високосний рік!",l.style.color="red",console.log("Ви народилися не у високосний рік!"),l.style.color="none"),e===0&&(l.textContent="Ви не ввели рік",l.style.color="red")});const h=document.querySelector(".yearNumber__number"),q=document.querySelector(".yearNumber__btn"),d=document.querySelector(".yearNumber__p");let f=Math.floor(Math.random()*10)+1;q.addEventListener("click",()=>{const e=Number(h.value);e===f?(d.textContent=`Вітаю, ви вгадали число! (${f})`,d.style.color="green"):(d.textContent=`Нажаль, ви не вгадали число! (${f})`,d.style.color="red"),f=Math.floor(Math.random()*10)+1,e===0&&(d.textContent="Ви не ввели число",d.style.color="red")});let y=0,b=0,v=0;const N=document.querySelectorAll("li.rock__item > button"),i=document.getElementById("message");document.getElementById("computerChoise");const k=document.getElementById("score");document.querySelector(".rock__button");N.forEach((e,t)=>{e.addEventListener("click",n=>{const a=t,o=Math.floor(Math.random()*3);$(a,o)})});const w=(e,t,n)=>{k.textContent=`Рахунок:
Комп’ютер - ${e}
Ви - ${t}
Нічия - ${n}`},$=(e,t)=>{const n="Нічия",a="Ви виграли раунд!",o="Комп’ютер виграв раунд!";return i.classList.remove("colorwin","colorlosse","color__draws"),e===t?(i.textContent=n,v=v+1,i.classList.add("color__draws")):e===0&&t===1||e===1&&t===2||e===2&&t===0?(i.textContent=a,y=y+1,i.classList.add("color__win")):(e===0&&t===2||e===1&&t===0||e===2&&t===1)&&(i.textContent=o,b=b+1,i.classList.add("color__losse")),w(b,y,v),i.textContent},M=document.querySelector(".calculator__number"),R=document.querySelector(".calculator__secondNumber"),u=document.querySelector(".calculator__result"),c=document.querySelector(".calculator__plus"),A=document.querySelector(".calculator__multiply"),C=document.querySelector(".calculator__divide"),B=document.querySelector(".calculator__minus"),j=document.querySelector(".calculator__calculate");j.addEventListener("click",()=>{c.addEventListener("click",()=>{c.classList.add("active1")}),A.addEventListener("click",()=>{c.classList.add("active2")}),C.addEventListener("click",()=>{c.classList.add("active3")}),B.addEventListener("click",()=>{c.classList.add("active4")});const e=Number(M.value),t=Number(R.value);let n=0;c.classList.contains("active1")?(n=e+t,u.textContent=n,c.classList.remove("active1")):c.classList.contains("active2")?(n=e*t,u.textContent=n,c.classList.remove("active2")):c.classList.contains("active3")?(n=e/t,u.textContent=n,c.classList.remove("active3"),t===0&&(u.textContent="неможливо")):c.classList.contains("active4")&&(n=e-t,u.textContent=n,c.classList.remove("active4"))});const p="/project3/assets/oleksii-4ab29b0e.webp",I="/project3/assets/sviatoslav-831eac03.webp",O="/project3/assets/alina-3e02aa95.webp",P="/project3/assets/lev-3dd1cf30.webp";console.log(p);const T=[{img:p,name:"Олексій",done:"Team lead, секції: calculator і dinosaur"},{img:I,name:"Святослав",done:"Scrum-master, секції: yearNumber, team і footer"},{img:O,name:"Аліна",done:"Розробляла секції: rock, football і scientists"},{img:P,name:"Лев",done:"Розробляв секції: header, footermodal і modal"}],g=document.querySelector(".team__list");function H({img:e,name:t,done:n}){return`<li class="team__item">
            <img src="${e}" alt="${t}" class="team__img">
            <h2 class="team__text">${t}</h2>
            <h3 class="team__description">${n}</h3>

          </li>`}const G=T.map(H).join("");g.innerHTML=G;const E=document.querySelectorAll(".team__item"),L=document.querySelectorAll(".team__box"),K=document.querySelector(".team__button-left"),Y=document.querySelector(".team__button-right");let s=0;window.addEventListener("keydown",e=>{e.key==="ArrowRight"&&s<E.length-1&&(s+=1,_()),e.key==="ArrowLeft"&&s>0&&(s-=1,_())});function _(){const e=-s*100;g.style.transform=`translateX(${e}%)`,console.log(e),L.forEach(t=>t.classList.remove("team__active")),L[s].classList.add("team__active")}Y.addEventListener("click",()=>{s<E.length-1&&(s+=1,_())});K.addEventListener("click",()=>{s>0&&(s-=1,_())});const W=[{name:"Albert",surname:"Einstein",born:1879,dead:1955,id:1},{name:"Isaac",surname:"Newton",born:1643,dead:1727,id:2},{name:"Galileo",surname:"Galilei",born:1564,dead:1642,id:3},{name:"Marie",surname:"Curie",born:1867,dead:1934,id:4},{name:"Johannes",surname:"Kepler",born:1571,dead:1630,id:5},{name:"Nicolaus",surname:"Copernicus",born:1473,dead:1543,id:6},{name:"Max",surname:"Planck",born:1858,dead:1947,id:7},{name:"Katherine",surname:"Blodgett",born:1898,dead:1979,id:8},{name:"Ada",surname:"Lovelace",born:1815,dead:1852,id:9},{name:"Sarah E.",surname:"Goode",born:1855,dead:1905,id:10},{name:"Lise",surname:"Meitner",born:1878,dead:1968,id:11},{name:"Hanna",surname:"Hammarström",born:1829,dead:1909,id:12}],F=document.querySelector(".scientists__list");function J(e){const t=e.map(({name:n,surname:a,born:o,dead:r,id:m})=>`
<li class="scientists__box">
      <h2>${n}</h2>
      <h3>${a}</h3>
      <p>${o}</p>
      <p>${r}</p>
    </li>`).join("");F.innerHTML=t}J(W);
//# sourceMappingURL=commonHelpers.js.map
