(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))a(n);new MutationObserver(n=>{for(const r of n)if(r.type==="childList")for(const m of r.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function o(n){const r={};return n.integrity&&(r.integrity=n.integrity),n.referrerPolicy&&(r.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?r.credentials="include":n.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(n){if(n.ep)return;n.ep=!0;const r=o(n);fetch(n.href,r)}})();const E=document.querySelector(".yearNumber__year"),S=document.querySelector(".yearNumber__button"),l=document.querySelector(".yearNumber__description");S.addEventListener("click",()=>{let e=Number(E.value);console.log(e),e%4===0&&e%100!==0||e%400===0?(l.textContent="Ви народилися у високосний рік!",l.style.color="green",console.log("Ви народилися у високосний рік!"),l.style.color="none"):(l.textContent="Ви народилися не у високосний рік!",l.style.color="red",console.log("Ви народилися не у високосний рік!"),l.style.color="none"),e===0&&(l.textContent="Ви не ввели рік",l.style.color="red")});const x=document.querySelector(".yearNumber__number"),h=document.querySelector(".yearNumber__btn"),d=document.querySelector(".yearNumber__p");let f=Math.floor(Math.random()*10)+1;h.addEventListener("click",()=>{const e=Number(x.value);e===f?(d.textContent=`Вітаю, ви вгадали число! (${f})`,d.style.color="green"):(d.textContent=`Нажаль, ви не вгадали число! (${f})`,d.style.color="red"),f=Math.floor(Math.random()*10)+1,e===0&&(d.textContent="Ви не ввели число",d.style.color="red")});let y=0,b=0,v=0;const q=document.querySelectorAll("li.rock__item > button"),i=document.getElementById("message");document.getElementById("computerChoise");const N=document.getElementById("score");document.querySelector(".rock__button");q.forEach((e,t)=>{e.addEventListener("click",o=>{const a=t,n=Math.floor(Math.random()*3);k(a,n)})});const w=(e,t,o)=>{N.textContent=`Рахунок:
Комп’ютер - ${e}
Ви - ${t}
Нічия - ${o}`},k=(e,t)=>{const o="Нічия",a="Ви виграли раунд!",n="Комп’ютер виграв раунд!";return i.classList.remove("colorwin","colorlosse","color__draws"),e===t?(i.textContent=o,v=v+1,i.classList.add("color__draws")):e===0&&t===1||e===1&&t===2||e===2&&t===0?(i.textContent=a,y=y+1,i.classList.add("color__win")):(e===0&&t===2||e===1&&t===0||e===2&&t===1)&&(i.textContent=n,b=b+1,i.classList.add("color__losse")),w(b,y,v),i.textContent},$=document.querySelector(".calculator__number"),M=document.querySelector(".calculator__secondNumber"),u=document.querySelector(".calculator__result"),c=document.querySelector(".calculator__plus"),R=document.querySelector(".calculator__multiply"),A=document.querySelector(".calculator__divide"),C=document.querySelector(".calculator__minus"),B=document.querySelector(".calculator__calculate");B.addEventListener("click",()=>{c.addEventListener("click",()=>{c.classList.add("active1")}),R.addEventListener("click",()=>{c.classList.add("active2")}),A.addEventListener("click",()=>{c.classList.add("active3")}),C.addEventListener("click",()=>{c.classList.add("active4")});const e=Number($.value),t=Number(M.value);let o=0;c.classList.contains("active1")?(o=e+t,u.textContent=o,c.classList.remove("active1")):c.classList.contains("active2")?(o=e*t,u.textContent=o,c.classList.remove("active2")):c.classList.contains("active3")?(o=e/t,u.textContent=o,c.classList.remove("active3"),t===0&&(u.textContent="неможливо")):c.classList.contains("active4")&&(o=e-t,u.textContent=o,c.classList.remove("active4"))});const I=[{img:"./img/oleksii.webp",name:"Олексій",done:"Team lead, секції: calculator і dinosaur"},{img:"./img/sviatoslav.webp",name:"Святослав",done:"Scrum-master, секції: yearNumber, team і footer"},{img:"./img/alina.webp",name:"Аліна",done:"Розробляла секції: rock, football і scientists"},{img:"./img/lev.webp",name:"Лев",done:"Розробляв секції: header, footermodal і modal"}],g=document.querySelector(".team__list");function O({img:e,name:t,done:o}){return`<li class="team__item">
            <img src="${e}" alt="${t}" class="team__img">
            <h2 class="team__text">${t}</h2>
            <h3 class="team__description">${o}</h3>

          </li>`}const P=I.map(O).join("");g.innerHTML=P;const p=document.querySelectorAll(".team__item"),L=document.querySelectorAll(".team__box"),T=document.querySelector(".team__button-left"),H=document.querySelector(".team__button-right");let s=0;window.addEventListener("keydown",e=>{e.key==="ArrowRight"&&s<p.length-1&&(s+=1,_()),e.key==="ArrowLeft"&&s>0&&(s-=1,_())});function _(){const e=-s*100;g.style.transform=`translateX(${e}%)`,console.log(e),L.forEach(t=>t.classList.remove("team__active")),L[s].classList.add("team__active")}H.addEventListener("click",()=>{s<p.length-1&&(s+=1,_())});T.addEventListener("click",()=>{s>0&&(s-=1,_())});const j=[{name:"Albert",surname:"Einstein",born:1879,dead:1955,id:1},{name:"Isaac",surname:"Newton",born:1643,dead:1727,id:2},{name:"Galileo",surname:"Galilei",born:1564,dead:1642,id:3},{name:"Marie",surname:"Curie",born:1867,dead:1934,id:4},{name:"Johannes",surname:"Kepler",born:1571,dead:1630,id:5},{name:"Nicolaus",surname:"Copernicus",born:1473,dead:1543,id:6},{name:"Max",surname:"Planck",born:1858,dead:1947,id:7},{name:"Katherine",surname:"Blodgett",born:1898,dead:1979,id:8},{name:"Ada",surname:"Lovelace",born:1815,dead:1852,id:9},{name:"Sarah E.",surname:"Goode",born:1855,dead:1905,id:10},{name:"Lise",surname:"Meitner",born:1878,dead:1968,id:11},{name:"Hanna",surname:"Hammarström",born:1829,dead:1909,id:12}],G=document.querySelector(".scientists__list");function K(e){const t=e.map(({name:o,surname:a,born:n,dead:r,id:m})=>`
<li class="scientists__box">
      <h2>${o}</h2>
      <h3>${a}</h3>
      <p>${n}</p>
      <p>${r}</p>
    </li>`).join("");G.innerHTML=t}K(j);
//# sourceMappingURL=commonHelpers.js.map
