(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))s(n);new MutationObserver(n=>{for(const o of n)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function r(n){const o={};return n.integrity&&(o.integrity=n.integrity),n.referrerPolicy&&(o.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?o.credentials="include":n.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(n){if(n.ep)return;n.ep=!0;const o=r(n);fetch(n.href,o)}})();const h=document.querySelector(".yearNumber__year"),L=document.querySelector(".yearNumber__button"),c=document.querySelector(".yearNumber__description");L.addEventListener("click",()=>{let e=Number(h.value);console.log(e),e%4===0&&e%100!==0||e%400===0?(c.textContent="Ви народилися у високосний рік!",c.style.color="green",console.log("Ви народилися у високосний рік!"),c.style.color="none"):(c.textContent="Ви народилися не у високосний рік!",c.style.color="red",console.log("Ви народилися не у високосний рік!"),c.style.color="none"),e===0&&(c.textContent="Ви не ввели рік",c.style.color="red")});const v=document.querySelector(".yearNumber__number"),x=document.querySelector(".yearNumber__btn"),i=document.querySelector(".yearNumber__p");let m=Math.floor(Math.random()*10)+1;x.addEventListener("click",()=>{const e=Number(v.value);e===m?(i.textContent=`Вітаю, ви вгадали число! (${m})`,i.style.color="green"):(i.textContent=`Нажаль, ви не вгадали число! (${m})`,i.style.color="red"),m=Math.floor(Math.random()*10)+1,e===0&&(i.textContent="Ви не ввели число",i.style.color="red")});let f=0,y=0,_=0;const S=document.querySelectorAll("li.rock__item > button"),l=document.getElementById("message");document.getElementById("computerChoise");const w=document.getElementById("score");document.querySelector(".rock__button");S.forEach((e,t)=>{e.addEventListener("click",r=>{const s=t,n=Math.floor(Math.random()*3);E(s,n)})});const N=(e,t,r)=>{w.textContent=`Рахунок:
Комп’ютер - ${e}
Ви - ${t}
Нічия - ${r}`},E=(e,t)=>{const r="Нічия",s="Ви виграли раунд!",n="Комп’ютер виграв раунд!";return l.classList.remove("colorwin","colorlosse","color__draws"),e===t?(l.textContent=r,_=_+1,l.classList.add("color__draws")):e===0&&t===1||e===1&&t===2||e===2&&t===0?(l.textContent=s,f=f+1,l.classList.add("color__win")):(e===0&&t===2||e===1&&t===0||e===2&&t===1)&&(l.textContent=n,y=y+1,l.classList.add("color__losse")),N(y,f,_),l.textContent},q=[{img:"../img/oleksii.webp",name:"Олексій",done:"Team lead, секції: calculator і dinosaur"},{img:"../img/sviatoslav.webp",name:"Святослав",done:"Scrum-master, секції: yearNumber, team і footer"},{img:"../img/alina.webp",name:"Аліна",done:"Розробляла секції: rock, football і scientists"},{img:"../img/lev.webp",name:"Лев",done:"Розробляв секції: header, footermodal і modal"}],g=document.querySelector(".team__list");function $({img:e,name:t,done:r}){return`<li class="team__item">
            <img src="${e}" alt="${t}" class="team__img">
            <h2 class="team__text">${t}</h2>
            <h3 class="team__description">${r}</h3>

          </li>`}const M=q.map($).join("");g.innerHTML=M;const p=document.querySelectorAll(".team__item"),b=document.querySelectorAll(".team__box"),R=document.querySelector(".team__button-left"),k=document.querySelector(".team__button-right");let a=0;window.addEventListener("keydown",e=>{e.key==="ArrowRight"&&a<p.length-1&&(a+=1,u()),e.key==="ArrowLeft"&&a>0&&(a-=1,u())});function u(){const e=-a*100;g.style.transform=`translateX(${e}%)`,console.log(e),b.forEach(t=>t.classList.remove("team__active")),b[a].classList.add("team__active")}k.addEventListener("click",()=>{a<p.length-1&&(a+=1,u())});R.addEventListener("click",()=>{a>0&&(a-=1,u())});const A=[{name:"Albert",surname:"Einstein",born:1879,dead:1955,id:1},{name:"Isaac",surname:"Newton",born:1643,dead:1727,id:2},{name:"Galileo",surname:"Galilei",born:1564,dead:1642,id:3},{name:"Marie",surname:"Curie",born:1867,dead:1934,id:4},{name:"Johannes",surname:"Kepler",born:1571,dead:1630,id:5},{name:"Nicolaus",surname:"Copernicus",born:1473,dead:1543,id:6},{name:"Max",surname:"Planck",born:1858,dead:1947,id:7},{name:"Katherine",surname:"Blodgett",born:1898,dead:1979,id:8},{name:"Ada",surname:"Lovelace",born:1815,dead:1852,id:9},{name:"Sarah E.",surname:"Goode",born:1855,dead:1905,id:10},{name:"Lise",surname:"Meitner",born:1878,dead:1968,id:11},{name:"Hanna",surname:"Hammarström",born:1829,dead:1909,id:12}],B=document.querySelector(".scientists__list");function I(e){const t=e.map(({name:r,surname:s,born:n,dead:o,id:d})=>`
<li class="scientists__box">
      <h2>${r}</h2>
      <h3>${s}</h3>
      <p>${n}</p>
      <p>${o}</p>
    </li>`).join("");B.innerHTML=t}I(A);
//# sourceMappingURL=commonHelpers.js.map
